# Generated by Django 3.2.3 on 2021-07-01 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0003_alter_product_selling_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('product', models.IntegerField()),
                ('ratings', models.IntegerField(default=0)),
            ],
        ),
    ]
