# Generated by Django 3.2.3 on 2021-07-02 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0004_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('interests', models.CharField(max_length=255)),
            ],
        ),
    ]
