# Generated by Django 3.2.3 on 2021-07-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Paypal', 'Paypal')], default='Cash On Delivery', max_length=20),
        ),
    ]
