# Generated by Django 3.2.3 on 2021-07-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='fields',
        ),
    ]
