# Generated by Django 3.2.3 on 2021-07-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210706_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('V', 'Vegetables'), ('F', 'Fruits'), ('LH', 'Leafy and Herbs')], max_length=2),
        ),
    ]
