# Generated by Django 3.2.3 on 2021-07-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='latitute',
            new_name='latitude',
        ),
    ]
