# Generated by Django 3.2.3 on 2021-07-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_latitute_customer_latitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='longitude',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='ktm', max_length=225),
        ),
    ]
