# Generated by Django 3.2.3 on 2021-07-23 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210721_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
    ]
